"""党史专题媒体目录。

真实照片只收录能够从 Wikimedia Commons 文件页核对主题和许可的资源；
其余专题使用脚本生成的项目自制信息图，不用无关风景图片填充。
"""

from __future__ import annotations


CURATED_COMMONS_MEDIA = {
    "may-fourth": {
        "filename": "Peking University Red Building.jpg",
        "section_id": "历史背景",
        "title": "北京大学红楼当代实景",
        "location": "北京市东城区",
        "year": "2019",
        "media_type": "当代实景",
        "caption": "图为北京大学红楼当代实景。该建筑与新文化运动、五四运动相关，本图用于对应本节所述思想传播背景，不是1919年历史现场照片。",
    },
    "party-founding": {
        "filename": "Site of the First National Congress of the CPC - 2025.jpg",
        "section_id": "形成与发展",
        "title": "中共一大会址当代实景",
        "location": "上海市黄浦区",
        "year": "2025",
        "media_type": "革命旧址照片",
        "caption": "图为上海中共一大会址当代实景，与本节所述中国共产党成立过程直接相关；属于2025年拍摄的旧址照片，不是1921年会议现场影像。",
    },
    "first-congress": {
        "filename": "Site of the First National Congress of the CPC - 2025.jpg",
        "section_id": "形成与发展",
        "title": "中共一大会址当代实景",
        "location": "上海市黄浦区",
        "year": "2025",
        "media_type": "革命旧址照片",
        "caption": "图为上海中共一大会址当代实景，与本节中共一大会议地点相对应；属于当代旧址照片，不是会议历史现场照片。",
    },
    "nanchang-uprising": {
        "filename": "Memorial tower of Nanchang Uprising.jpg",
        "section_id": "形成与发展",
        "title": "八一南昌起义纪念塔",
        "location": "江西省南昌市",
        "year": "2009",
        "media_type": "纪念设施照片",
        "caption": "图为八一南昌起义纪念塔当代照片，地点与本节所述南昌起义相对应；用于展示纪念设施，不是1927年起义现场照片。",
    },
    "jinggangshan-base": {
        "filename": "井冈山革命博物馆 01.jpg",
        "section_id": "历史背景",
        "title": "井冈山革命博物馆",
        "location": "江西省井冈山市茨坪",
        "year": "2019",
        "media_type": "纪念馆照片",
        "caption": "图为井冈山革命博物馆当代实景，与本节井冈山革命根据地的地点和纪念展示相对应；不是革命斗争历史现场照片。",
    },
    "gutian-meeting": {
        "filename": "Gutian entrance.jpg",
        "section_id": "历史背景",
        "title": "古田会议会址入口",
        "location": "福建省龙岩市上杭县古田镇",
        "year": "当代拍摄",
        "media_type": "革命旧址照片",
        "caption": "图为古田会议会址入口当代实景，与本节所述古田会议地点直接对应；属于旧址照片，不是1929年会议现场影像。",
    },
    "long-march": {
        "filename": "Liupanshan Red Army Long March Memorial Hall (20260201154058).jpg",
        "section_id": "历史意义与当代价值",
        "title": "六盘山红军长征纪念馆",
        "location": "宁夏回族自治区固原市六盘山地区",
        "year": "2026",
        "media_type": "纪念馆照片",
        "caption": "图为六盘山红军长征纪念馆当代实景，用于对应本节长征记忆与当代纪念展示；不是长征历史现场照片，也不用于替代长征路线图。",
    },
    "zunyi-meeting": {
        "filename": "Site of Zunyi Conference (20180220101816).jpg",
        "section_id": "历史背景",
        "title": "遵义会议会址",
        "location": "贵州省遵义市红花岗区",
        "year": "2018",
        "media_type": "革命旧址照片",
        "caption": "图为遵义会议会址当代实景，位于贵州省遵义市，与本节所述遵义会议地点直接对应；不是1935年会议现场照片。",
    },
    "yanan-period": {
        "filename": "延安宝塔夜景.png",
        "section_id": "历史背景",
        "title": "延安宝塔山当代实景",
        "location": "陕西省延安市",
        "year": "2012",
        "media_type": "当代实景",
        "caption": "图为延安宝塔山当代实景，用于展示延安红色文化地标，与本节延安时期的空间背景相对应；不是历史现场照片。",
    },
    "xibaipo": {
        "filename": "Xibaipo Memorial Hall (20240609100945).jpg",
        "section_id": "历史背景",
        "title": "西柏坡纪念馆",
        "location": "河北省石家庄市平山县西柏坡镇",
        "year": "2024",
        "media_type": "纪念馆照片",
        "caption": "图为西柏坡纪念馆当代实景，与本节所述西柏坡时期和纪念展示直接对应；属于纪念馆照片，不是1948至1949年的历史现场影像。",
    },
    "resist-us-aid-korea": {
        "filename": "Memorial Tower to Resist U.S. Aggression and Aid Korea.jpg",
        "section_id": "历史意义与当代价值",
        "title": "抗美援朝纪念塔",
        "location": "辽宁省丹东市",
        "year": "2024",
        "media_type": "纪念设施照片",
        "caption": "图为辽宁丹东抗美援朝纪念塔当代实景，与本节抗美援朝纪念主题相对应；不是战争现场照片。",
    },
    "reform-opening": {
        "filename": "SZ 深圳博物館 Shenzhen Museum exhibition rooms Reform and Opening-Up History signs Sept 2017 IX1.jpg",
        "section_id": "历史意义与当代价值",
        "title": "深圳博物馆改革开放史展厅",
        "location": "广东省深圳市",
        "year": "2017",
        "media_type": "纪念馆照片",
        "caption": "图为深圳博物馆改革开放史展厅当代照片，用于对应本节改革开放历史展示与公共教育内容；不是1978年历史现场照片。",
    },
}


MEDIA_TYPE_LABELS = {
    "历史原始照片",
    "历史档案资料",
    "人物照片",
    "革命旧址照片",
    "纪念馆照片",
    "纪念设施照片",
    "历史地图",
    "路线示意",
    "当代实景",
    "复原图",
    "艺术创作",
    "山岳风光示意",
    "项目自制",
}


CURATED_FIGURES = {
    "mao-zedong-1919": {
        "name": "毛泽东",
        "filename": "Mao Zedong 1919.jpg",
        "active_period": "1893—1976",
        "biography": "毛泽东是伟大的马克思主义者，无产阶级革命家、战略家和理论家，中国共产党、中国人民解放军和中华人民共和国的主要缔造者和领导人之一。",
        "deeds": "参与创建中国共产党，领导中国革命和建设的长期实践。平台人物页只作全国党史学习索引，具体历史评价以权威党史文献为准。",
        "related_events": "五四运动与马克思主义传播、秋收起义、井冈山革命根据地、遵义会议、延安时期、中华人民共和国成立",
        "photo_note": "毛泽东1919年人物照片，人物、年份与文件页说明一致。",
        "photo_type": "人物照片",
    },
    "zhou-enlai-1972": {
        "name": "周恩来",
        "filename": "Zhou Enlai 1972.jpg",
        "active_period": "1898—1976",
        "biography": "周恩来是伟大的马克思主义者，无产阶级革命家、政治家、军事家、外交家，党和国家主要领导人之一。",
        "deeds": "参与党和人民军队创建发展的重要实践，在革命、建设和外交工作中承担重要职责。",
        "related_events": "中国共产党成立、南昌起义、红军长征、遵义会议、中华人民共和国成立",
        "photo_note": "周恩来1972年人物照片，来源为美国国家档案相关公开资料；不是雕塑或影视剧照。",
        "photo_type": "人物照片",
    },
    "zhu-de-1922": {
        "name": "朱德",
        "filename": "Zhu De (1922).jpg",
        "active_period": "1886—1976",
        "biography": "朱德是伟大的马克思主义者，无产阶级革命家、政治家和军事家，中国人民解放军主要缔造者和领导人之一。",
        "deeds": "参加领导南昌起义，参与井冈山会师和人民军队建设，为中国革命和建设作出重要贡献。",
        "related_events": "南昌起义、井冈山革命根据地、红军长征、抗日战争、解放战争",
        "photo_note": "朱德1922年人物照片，人物与年份按 Wikimedia Commons 文件页核对。",
        "photo_type": "人物照片",
    },
    "deng-xiaoping-1979": {
        "name": "邓小平",
        "filename": "Deng Xiaoping.jpg",
        "active_period": "1904—1997",
        "biography": "邓小平是伟大的马克思主义者，无产阶级革命家、政治家、军事家、外交家，中国社会主义改革开放和现代化建设的总设计师。",
        "deeds": "在革命、建设和改革各历史时期承担重要工作，推动党和国家工作中心转移以及改革开放和社会主义现代化建设。",
        "related_events": "红军长征、抗日战争、解放战争、改革开放",
        "photo_note": "邓小平1979年人物照片，来源为美国国家档案馆公开资料；不是艺术形象。",
        "photo_type": "人物照片",
    },
}

# 以下肖像由 Wikidata 人物实体的 P18 字段定位，并在 Wikimedia Commons
# 文件页读取作者和许可信息。文件名必须与 Commons 页面完全一致。
CURATED_FIGURES.update({
    "liu-shaoqi": {
        "name": "刘少奇",
        "filename": "Liu Shaoqi (cropped).jpg",
        "photo_note": "刘少奇人物照片，人物身份由 Wikidata Q16988 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "ren-bishi": {
        "name": "任弼时",
        "filename": "1938 Chinese Comintern Ren Bishi.jpg",
        "photo_note": "任弼时人物照片，人物身份由 Wikidata Q715411 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "chen-yun": {
        "name": "陈云",
        "filename": "1958 Chenyun.jpg",
        "photo_note": "陈云人物照片，人物身份由 Wikidata Q557233 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "dong-biwu": {
        "name": "董必武",
        "filename": "DONGBIWU.JPG",
        "photo_note": "董必武人物照片，人物身份由 Wikidata Q968038 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "peng-dehuai": {
        "name": "彭德怀",
        "filename": "General Peng Dehuai.jpg",
        "photo_note": "彭德怀人物照片，人物身份由 Wikidata Q381823 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "lin-boqu": {
        "name": "林伯渠",
        "filename": "Lin Boqu2.jpg",
        "photo_note": "林伯渠人物照片，人物身份由 Wikidata Q700523 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "he-long": {
        "name": "贺龙",
        "filename": "He Long.jpg",
        "photo_note": "贺龙人物照片，人物身份由 Wikidata Q700713 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "liu-bocheng": {
        "name": "刘伯承",
        "filename": "Liu Bocheng.jpg",
        "photo_note": "刘伯承人物照片，人物身份由 Wikidata Q701507 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "chen-yi": {
        "name": "陈毅",
        "filename": "Chen Yi(communist).jpg",
        "photo_note": "陈毅人物照片，人物身份由 Wikidata Q188408 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "nie-rongzhen": {
        "name": "聂荣臻",
        "filename": "Marshal Nie Rongzhen.jpg",
        "photo_note": "聂荣臻人物照片，人物身份由 Wikidata Q701453 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "xu-xiangqian": {
        "name": "徐向前",
        "filename": "Xu Xiangqian.jpg",
        "photo_note": "徐向前人物照片，人物身份由 Wikidata Q702194 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "ye-jianying": {
        "name": "叶剑英",
        "filename": "Ye Jianying.jpg",
        "photo_note": "叶剑英人物照片，人物身份由 Wikidata Q504372 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "luo-ronghuan": {
        "name": "罗荣桓",
        "filename": "Luo Ronghuan.jpg",
        "photo_note": "罗荣桓人物照片，人物身份由 Wikidata Q709545 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "su-yu": {
        "name": "粟裕",
        "filename": "Su Yu 1955 formal.jpg",
        "photo_note": "粟裕人物照片，人物身份由 Wikidata Q840370 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "lei-feng": {
        "name": "雷锋",
        "filename": "Lei Feng 13.jpg",
        "photo_note": "雷锋人物照片，人物身份由 Wikidata Q379835 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "jiao-yulu": {
        "name": "焦裕禄",
        "filename": "Jiaoyulu.jpg",
        "photo_note": "焦裕禄人物照片，人物身份由 Wikidata Q8288518 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "wang-jinxi": {
        "name": "王进喜",
        "filename": "1966-07 大庆铁人王进喜.jpg",
        "photo_note": "王进喜人物照片，人物身份由 Wikidata Q8294602 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "qian-xuesen": {
        "name": "钱学森",
        "filename": "Tsien Hsue-shen.jpg",
        "photo_note": "钱学森人物照片，人物身份由 Wikidata Q333500 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "deng-jiaxian": {
        "name": "邓稼先",
        "filename": "鄧稼先普渡照片.jpg",
        "photo_note": "邓稼先人物照片，人物身份由 Wikidata Q5256919 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "guo-yonghuai": {
        "name": "郭永怀",
        "filename": "郭永懷.jpg",
        "photo_note": "郭永怀人物照片，人物身份由 Wikidata Q1555112 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "yuan-longping": {
        "name": "袁隆平",
        "filename": "Yuan Longping at news conference (cropped).png",
        "photo_note": "袁隆平人物照片，人物身份由 Wikidata Q3141326 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "huang-xuhua": {
        "name": "黄旭华",
        "filename": "Huang Xuhua in 1952 (image only).jpg",
        "photo_note": "黄旭华人物照片，人物身份由 Wikidata Q8972150 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "tu-youyou": {
        "name": "屠呦呦",
        "filename": "D810 4987 Tu Youyou, medicine (22945001843) (cropped).jpg",
        "photo_note": "屠呦呦人物照片，人物身份由 Wikidata Q462843 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "yang-liwei": {
        "name": "杨利伟",
        "filename": "Yang Liwei.jpg",
        "photo_note": "杨利伟人物照片，人物身份由 Wikidata Q147581 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "zhang-fuqing": {
        "name": "张富清",
        "filename": "Zhang Fuqing.jpg",
        "photo_note": "张富清人物照片，人物身份由 Wikidata Q65061667 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
    "shen-jilan": {
        "name": "申纪兰",
        "filename": "Shen Jilan.jpg",
        "photo_note": "申纪兰人物照片，人物身份由 Wikidata Q8246757 与 Commons 文件页交叉核对。",
        "photo_type": "人物照片",
    },
})


# 未配置可靠肖像的条目使用项目自制人物档案图解，不冒充人物照片。
FIGURE_PROFILES = {
    "毛泽东": ("1893—1976", "中国共产党、中国人民解放军和中华人民共和国的主要缔造者和领导人之一", "参与创建中国共产党，领导中国革命和建设的长期实践。", "中共一大、井冈山、遵义会议、延安时期、新中国成立"),
    "周恩来": ("1898—1976", "伟大的无产阶级革命家、政治家、军事家、外交家", "在党、人民军队和新中国创建发展历程中承担重要职责。", "中国共产党成立、南昌起义、长征、遵义会议、新中国成立"),
    "朱德": ("1886—1976", "伟大的无产阶级革命家、政治家、军事家", "参加领导南昌起义，参与井冈山会师和人民军队建设。", "南昌起义、井冈山、长征、抗日战争、解放战争"),
    "邓小平": ("1904—1997", "中国社会主义改革开放和现代化建设的总设计师", "在革命、建设和改革各时期承担重要工作，推动改革开放。", "长征、抗日战争、解放战争、改革开放"),
    "刘少奇": ("1898—1969", "伟大的马克思主义者和无产阶级革命家", "长期从事工人运动、党的建设和党和国家领导工作。", "工人运动、抗日战争、解放战争、社会主义建设"),
    "任弼时": ("1904—1950", "伟大的马克思主义者和无产阶级革命家", "为党的建设、红军长征和中国革命胜利作出重要贡献。", "中国共产党早期活动、红军长征、延安时期"),
    "陈云": ("1905—1995", "伟大的无产阶级革命家、政治家，杰出的马克思主义者", "在党的组织工作、经济工作和社会主义建设改革中承担重要职责。", "长征、延安时期、社会主义建设、改革开放"),
    "董必武": ("1886—1975", "中国共产党的创始人之一，伟大的无产阶级革命家", "参加中共一大，长期参与革命和新中国法制建设。", "中共一大、抗日战争、新中国成立"),
    "彭德怀": ("1898—1974", "无产阶级革命家、军事家，中国人民解放军重要领导人", "参加领导革命战争和国防建设，担任中国人民志愿军司令员兼政治委员。", "红军长征、抗日战争、解放战争、抗美援朝"),
    "林伯渠": ("1886—1960", "中国共产党和中华人民共和国重要领导人之一", "参加党的创建和长期革命实践，参与新中国筹建工作。", "中国共产党成立、长征、延安时期、新中国成立"),
    "贺龙": ("1896—1969", "无产阶级革命家、军事家，中国人民解放军创建人和领导人之一", "参加领导南昌起义，长期参与人民军队建设和革命战争。", "南昌起义、长征、抗日战争、解放战争"),
    "刘伯承": ("1892—1986", "无产阶级革命家、军事家，中国人民解放军创建人和领导人之一", "参加南昌起义、长征和抗日战争、解放战争，推进军事教育。", "南昌起义、长征、抗日战争、解放战争"),
    "陈毅": ("1901—1972", "无产阶级革命家、军事家、外交家", "参与革命根据地斗争、抗日战争和解放战争，后从事国防与外交工作。", "井冈山斗争、抗日战争、解放战争、新中国外交"),
    "聂荣臻": ("1899—1992", "无产阶级革命家、军事家，中国人民解放军创建人和领导人之一", "参加革命战争，中华人民共和国成立后参与国防科技事业领导工作。", "南昌起义、长征、抗日战争、两弹一星"),
    "徐向前": ("1901—1990", "无产阶级革命家、军事家，中国人民解放军创建人和领导人之一", "长期参加革命战争和人民军队建设。", "土地革命战争、长征、抗日战争、解放战争"),
    "叶剑英": ("1897—1986", "无产阶级革命家、政治家、军事家", "参加革命战争和新中国国防建设，在党和国家重要历史阶段承担职责。", "长征、抗日战争、解放战争、社会主义建设"),
    "罗荣桓": ("1902—1963", "无产阶级革命家、政治家、军事家", "长期从事人民军队政治工作，为军队建设作出重要贡献。", "秋收起义、井冈山、长征、解放战争"),
    "粟裕": ("1907—1984", "无产阶级革命家、军事家，中国人民解放军高级将领", "参加革命战争，在解放战争重要战役指挥中承担职责。", "南昌起义后革命斗争、抗日战争、解放战争"),
    "雷锋": ("1940—1962", "中国人民解放军战士、全国人民学习的楷模", "在平凡岗位服务人民，其事迹成为雷锋精神的重要实践载体。", "雷锋精神、社会主义建设时期"),
    "焦裕禄": ("1922—1964", "县委书记的榜样、人民的好公仆", "在河南兰考工作期间带领群众治理内涝、风沙、盐碱等困难。", "焦裕禄精神、社会主义建设时期"),
    "王进喜": ("1923—1970", "全国劳动模范、石油工人代表", "参加大庆石油会战，以艰苦奋斗实践形成铁人精神的鲜明标识。", "大庆石油会战、铁人精神"),
    "钱学森": ("1911—2009", "人民科学家、中国航天事业奠基人之一", "为中国导弹、航天和系统科学事业发展作出重要贡献。", "两弹一星、科学家精神、航天事业"),
    "邓稼先": ("1924—1986", "核物理学家，中国核武器研制工作的开拓者和奠基者之一", "长期参与并组织中国核武器理论研究与研制工作。", "两弹一星、科学家精神"),
    "郭永怀": ("1909—1968", "力学家、应用数学家，中国科学院学部委员", "参与力学研究和国防科技事业，为两弹一星事业作出重要贡献。", "两弹一星、科学家精神"),
    "袁隆平": ("1930—2021", "杂交水稻育种专家、共和国勋章获得者", "长期从事杂交水稻研究，为粮食安全和农业科技进步作出重要贡献。", "科学家精神、农业科技"),
    "黄旭华": ("1926—2025", "船舶工程专家、共和国勋章获得者", "长期投身核潜艇研制事业，为我国核潜艇事业发展作出重要贡献。", "科学家精神、国防科技"),
    "屠呦呦": ("1930年至今", "药学家、诺贝尔生理学或医学奖获得者", "带领团队从传统医药文献中获得启发，推进青蒿素研究。", "科学家精神、医药科技"),
    "杨利伟": ("1965年至今", "中国首位进入太空的航天员", "执行神舟五号载人航天飞行任务，为中国载人航天事业作出重要贡献。", "载人航天精神、神舟五号"),
    "张富清": ("1924—2022", "战斗英雄、全国优秀共产党员、共和国勋章获得者", "战争年代保家卫国，转业后扎根基层服务群众。", "革命战争、基层奉献"),
    "申纪兰": ("1929—2020", "全国劳动模范、共和国勋章获得者", "长期扎根农村，积极参与劳动和基层建设，倡导男女同工同酬。", "劳模精神、基层建设"),
}
